version: '2.1'

services:
  probate-frontend:
    build:
      context: .
    image: probate/probabte-frontend
    # image: docker.artifactory.reform.hmcts.net/probate/probate-frontend
    container_name: probate-frontend
    environment:
      - USE_HTTPS=false
      - USE_AUTH=false
      - USE_IDAM=false
      - VALIDATION_SERVICE_URL=http://business-service:8081/validate
      - CHECK_ANSWERS_PDF_SERVICE_URL=http://business-service:8080/businessDocument/generateCheckAnswersSummaryPDF
      - SUBMIT_SERVICE_URL=http://submit-service:8181/submit
      - PERSISTENCE_SERVICE_URL=http://persistence-service:8282/formdata
      - http_proxy=
      - https_proxy=
      - no_proxy=
    ports:
     - 3000:3000
    links:
     - business-service
     - submit-service
     - persistence-service
    depends_on:
     - business-service
     - submit-service
     - persistence-service
    networks:
      default:
        aliases:
          - https://www-local.probate.reform.hmcts.net

  business-service:
    image: probate/business-service
    container_name: business-service
    environment:
      - SERVER_PORT=8081
      - http_proxy=
      - https_proxy=
      - no_proxy=
    ports:
     - 8081:8081

  submit-service:
    image: probate/submit-service
    container_name: submit-service
    environment:
      - SERVER_PORT=8181
      - PROBATE_MAIL_HOST=idam-postfix
      - PROBATE_MAIL_PORT=25
      - PROBATE_MAIL_USERNAME=localhost
      - PROBATE_MAIL_PASSWORD=Pr0bate!23
      - PROBATE_MAIL_SENDER=probate-application@hmcts.net
      - PROBATE_MAIL_RECIPIENT=test.probate.inbox@gmail.com
      - PROBATE_PERSISTENCE_HOSTNAME=persistence-service:8282
      - http_proxy=
      - https_proxy=
      - no_proxy=
    ports:
     - 8181:8181
    depends_on:
      - idam-postfix

  persistence-service:
    image: probate/persistence-service
    command: --wait-for-database 30
    container_name: persistence-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://persistence-service-database:5432/probate
      - PROBATE_POSTGRESQL_HOSTNAME=persistence-service-database
      - PROBATE_POSTGRESQL_PORT=5432
      - PROBATE_POSTGRESQL_DATABASE=probate
      - PROBATE_POSTGRESQL_USER=probate
      - PROBATE_POSTGRESQL_PASSWORD=probate
      - PROBATE_PERSISTENCE_PORT=8282
      - http_proxy=
      - https_proxy=
      - no_proxy=
    ports:
     - 8282:8282
    links:
      - persistence-service-database
    depends_on:
      - persistence-service-database

  persistence-service-database:
    image: probate/persistence-service-database
    container_name: persistence-service-database
    ports:
      - 5432:5432
    volumes:
      - persistence-service-database-data:/var/lib/postgresql/data

  idam-postfix:
    image: catatnight/postfix
    container_name: idam-postfix
    environment:
        - maildomain=localhost
        - smtp_user=localhost:Pr0bate!23
    ports:
      - 25:25

volumes:
  persistence-service-database-data:

