environment: REFORM_ENVIRONMENT
nodeEnvironment: NODE_ENV
gitRevision: GIT_REVISION
frontendPublicHttpProtocol: PUBLIC_PROTOCOL
featureToggles:
  enabled: LAUNCHDARKLY_ENABLED
  launchDarklyKey: LAUNCHDARKLY_KEY
  launchDarklyUser:
    key: LAUNCHDARKLY_USER_KEY
configFeatureToggles:
  webchatEnabled: WEBCHAT_ENABLED
  gaEnabled: GA_ENABLED
app:
  username: USERNAME
  password: PASSWORD
  useIDAM: USE_IDAM
  requireCcdCaseId: REQUIRE_CCD_CASE_ID
  port: PORT
services:
  postcode:
    token: POSTCODE_SERVICE_TOKEN
  orchestrator:
    url: ORCHESTRATOR_SERVICE_URL
  validation:
    url: VALIDATION_SERVICE_URL
  idam:
    loginUrl: IDAM_LOGIN_URL
    apiUrl: IDAM_API_URL
    s2s_url: IDAM_S2S_URL
    service_key: IDAM_SERVICE_KEY
    probate_oauth2_client: IDAM_CLIENT_NAME
    probate_oauth2_secret: IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_PROBATE
    probate_user_email: PROBATE_USER_EMAIL
    probate_user_password: PROBATE_USER_PASSWORD
    probate_redirect_base_url: PROBATE_REDIRECT_BASE_URL
  payment:
    url: PAYMENT_API_URL
    authorization: PAYMENT_AUTHORIZATION
    serviceAuthorization: PAYMENT_SERVICE_AUTHORIZATION
    userId: PAYMENT_USER_ID
  pact:
    brokerUrl: PACT_BROKER_URL
    tag: PACT_BRANCH_NAME
  feesRegister:
    url: FEES_REGISTRY_URL
  equalityAndDiversity:
    url: EQUALITY_URL
    tokenKey: PROBATE_TOKEN_KEY
redis:
  host: REDIS_HOST
  port: REDIS_PORT
  password: REDIS_PASSWORD
  useTLS: REDIS_USE_TLS
  enabled: USE_REDIS
  secret: REDIS_SECRET
enableTracking: ENABLE_TRACKING
webchat:
  avayaUrl: WEBCHAT_AVAYA_URL
  avayaClientUrl: WEBCHAT_AVAYA_CLIENT_URL
  avayaService: WEBCHAT_AVAYA_SERVICE
links:
  survey: SURVEY
  surveyEndOfApplication: SURVEY_END_OF_APPLICATION
  terms: TERMS_AND_CONDITIONS
utils:
  api:
    retries: RETRIES_NUMBER
    retryDelay: RETRY_DELAY
payment:
  serviceId: SERVICE_ID
  siteId: SITE_ID
  version: version
  currency: currency

appInsights:
  connectionString: APP-INSIGHTS-CONNECTION-STRING

TestCitizenDomain: CITIZEN_EMAIL_DOMAIN
TestE2EFrontendUrl: TEST_URL
TestFrontendUrl: TEST_URL
TestIdamAddUserUrl: IDAM_ADD_USER_URL
TestIdamBaseUrl: IDAM_API_URL
TestIdamLoginUrl: IDAM_LOGIN_URL
TestIdamRole: IDAM_CITIZEN_ROLE
TestIdamUserGroup: IDAM_USER_GROUP
TestInvitationUrl: INVITATION_URL
TestInviteIdListUrl: INVITE_ID_LIST_URL
TestOutputDir: E2E_OUTPUT_DIR
TestPathToRun: FE_E2E_TEST_PATH_TO_RUN
TestPinUrl: PIN_URL
TestProxy: TEST_PROXY
TestRetryFeatures: RETRY_FEATURES
TestRetryScenarios: RETRY_SCENARIOS
TestRetrySteps: RETRY_STEPS
TestUseIdam: USE_IDAM
TestUseProxy: TEST_USE_PROXY

postcodeLookup:
  token: ADDRESS_TOKEN

TestEnvEmailAddress: TEST_EMAIL_ADDRESS
TestEnvMobileNumber: TEST_MOBILE_NUMBER

pact:
  pactBrokerUrl: PACT_BROKER_URL

exceptedEstateDateOfDeath: EXCEPTED_ESTATE_DATE_OF_DEATH
