environment: 'prod'
nodeEnvironment: 'production'
gitRevision: ''
frontendPublicHttpProtocol: http
languages: ['en', 'cy']
featureToggles:
  enabled: true
  launchDarklyKey: 'LAUNDARKLEY-KEY'
  launchDarklyUser:
    firstName: 'Probate'
    lastName: 'Frontend'
    key: 'LAUNCHDARKLY_USER_KEY'
  ft_fees_api: 'probate-fees-api'
  ft_pcq: 'probate-pcq'
  ft_pcq_token: 'probate-pcq-token'
  ft_avaya_webchat: 'probate-avaya-webchat'
  ft_newfee_register_code: 'probate-newfee-register-code'
  ft_excepted_estates: 'probate-excepted-estates'
  ft_will_condition : 'probate-will-condition'
  appwideToggles: ['ft_avaya_webchat']
# overrides featureToggles to e.g. switch off in pipeline/locally
configFeatureToggles:
  webchatEnabled: true
  gaEnabled: true
app:
  username:
  password:
  useAuth: 'false'
  useHttps: 'false'
  useIDAM: 'false'
  requireCcdCaseId: 'false'
  port: '3000'
  useCSRFProtection: 'true' # TODO: tech debt, tests should be csrf aware, it shouldn't be possible to accidentally disable this
  session:
    expires: 3600000 # ms (60 minutes)
    ttl: 28800 # ms (8 hours)
health:
  service_name: 'Apply for Probate'
  timeout: 5000
  deadline: 15000
services:
  postcode:
    name: 'Postcode Lookup Service'
    token:
  orchestrator:
    name: 'Orchestrator Service'
    url: 'http://localhost:8888'
    paths:
      forms: '/forms/case/{ccdCaseId}'
      create: '/forms/newcase/'
      submissions: '/forms/{ccdCaseId}/submissions'
      payments: '/forms/{ccdCaseId}/payments'
      payment_updates: '/payment-updates'
      payment_submissions: '/forms/{ccdCaseId}/payment-submissions'
      fees: '/forms/{ccdCaseId}/fees'
      validations: '/forms/{ccdCaseId}/validations'
      applications: '/forms/cases'
      declarationStatuses: '/invites/{ccdCaseId}'
    port: 8888
    gitCommitIdPath: 'git.commit.id'
  validation:
    name: 'Business Service'
    url: 'http://localhost:8081/validate'
    gitCommitIdPath: 'git.commit.id'
  idam:
    name: 'IdAM Service'
    loginUrl: 'http://localhost:3501/login'
    apiUrl: 'http://localhost:5000'
    roles: ['probate-private-beta', 'citizen']
    s2s_url: 'http://localhost:4502'
    service_name: 'probate_frontend'
    service_key: 'AAAAAAAAAAAAAAAA'
    probate_oauth2_client: 'ccd_gateway'
    probate_oauth2_secret: 'ccd_gateway_secret'
    probate_oauth_callback_path: '/oauth2/callback'
    probate_oauth_token_path: '/oauth2/token'
    probate_user_email: 'dummy-user-name'
    probate_user_password: 'dummy-password'
    probate_redirect_base_url: 'http://localhost:3000'
  payment:
    name: 'Payment Service'
    url: 'http://localhost:8383'
    authorization: 'DUMMY_TOKEN'
    serviceAuthorization: 'DUMMY_TOKEN'
    userId: 46
    paths:
      payments: '/payments'
      createPayment: '/card-payments'
      returnUrlPath: '/payment-status'
  pact:
    name: 'PACT Service'
    url: 'http://localhost:80'
    tag: 'Dev'
    pactDirectory: 'pacts'
  feesRegister:
    name: 'Fees Register Service'
    url: 'http://localhost:4411/fees-register'
    port: 4411
    paths:
      fees: '/fees'
      feesLookup: '/fees/lookup'
    ihtMinAmt: 5000
    issuesData:
      amount_or_volume: 0
      applicant_type: 'all'
      channel: 'default'
      event: 'issue'
      jurisdiction1: 'family'
      jurisdiction2: 'probate registry'
      service: 'probate'
    copiesData:
      amount_or_volume: 0
      applicant_type: 'all'
      channel: 'default'
      event: 'copies'
      jurisdiction1: 'family'
      jurisdiction2: 'probate registry'
      service: 'probate'
      keyword: 'NewFee'
    newfee_issuesData:
      amount_or_volume: 0
      applicant_type: 'all'
      channel: 'default'
      event: 'issue'
      jurisdiction1: 'family'
      jurisdiction2: 'probate registry'
      service: 'probate'
      keyword: 'SA'
    newfee_issuesDataIhtMinAmount:
      amount_or_volume: 0
      applicant_type: 'all'
      channel: 'default'
      event: 'issue'
      jurisdiction1: 'family'
      jurisdiction2: 'probate registry'
      service: 'probate'
      keyword: 'SAL5K'
    newfee_copiesData:
      amount_or_volume: 0
      applicant_type: 'all'
      channel: 'default'
      event: 'copies'
      jurisdiction1: 'family'
      jurisdiction2: 'probate registry'
      service: 'probate'
      keyword: 'GrantWill'
  equalityAndDiversity:
    name: 'Equality and Diversity Service'
    url: 'http://localhost:4000'
    path: '/service-endpoint'
    gitCommitIdPath: 'buildInfo.extra.gitCommitId'
    port: 4000
    tokenKey: 'PROBATE_TOKEN_KEY'
redis:
  host: 'localhost'
  port: 6379
  password: 'dummy_password'
  useTLS: 'false'
  enabled: 'false'
  secret: 'OVERWRITE_THIS'
  resave: false
  saveUninitialized: true
  cookie:
    httpOnly: true
    secure: true
  eligibilityCookie:
    name: '__eligibility'
    redirectUrl: '/start-eligibility'
    expires: 172800000 # 48 hours
dateFormat: 'DD/MM/YYYY'
payloadVersion: '4.1.1'
enableTracking: 'true'
webchat:
  avayaUrl: 'webchat.training.ctsc.hmcts.net'
  avayaClientUrl: 'webchat-client.training.ctsc.hmcts.net'
  avayaService: 'Testing'
links:
  accessibility: '/accessibility-statement'
  cookies: '/cookies'
  privacy: '/privacy-policy'
  terms: '/terms-conditions'
  contact: '/contact-us'
  webchat: '/avaya-webchat'
  callCharges: 'https://www.gov.uk/call-charges'
  howToManageCookies: 'https://www.aboutcookies.org'
  googlePrivacyPolicy: 'https://www.google.com/policies/privacy/partners/'
  googleAnalyticsOptOut: 'https://tools.google.com/dlpage/gaoptout/'
  mojPersonalInformationCharter: 'https://www.gov.uk/government/organisations/ministry-of-justice/about/personal-information-charter'
  goodThingsFoundation: 'https://www.goodthingsfoundation.org'
  subjectAccessRequest: 'https://www.gov.uk/government/publications/request-your-personal-data-from-moj'
  complaintsProcedure: 'https://www.gov.uk/government/organisations/hm-courts-and-tribunals-service/about/complaints-procedure'
  informationCommissionersOffice: 'https://ico.org.uk/global/contact-us'
  survey: 'https://www.smartsurvey.co.uk/s/Probate_Feedback/'
  surveyEndOfApplication: 'https://www.smartsurvey.co.uk/s/Probate_ExitSurvey/'
  ihtNotCompleted: 'https://www.gov.uk/valuing-estate-of-someone-who-died/tell-hmrc-estate-value'
  applicationFormPA15: 'https://www.gov.uk/government/publications/form-pa15-apply-for-renunciation-will'
  applicationFormPA1A: 'https://www.gov.uk/government/publications/form-pa1a-apply-for-probate-deceased-did-not-leave-a-will'
  applicationFormPA1P: 'https://www.gov.uk/government/publications/form-pa1p-apply-for-probate-the-deceased-had-a-will'
  applicationFormPA19: 'https://www.gov.uk/government/publications/form-pa19-apply-for-a-grant-of-representation-with-a-foreign-death-certificate-not-translated-by-a-licensed-company'
  deathCertificate: 'https://www.gov.uk/order-copy-birth-death-marriage-certificate'
  deathReportedToCoroner: 'https://www.gov.uk/after-a-death/when-a-death-is-reported-to-a-coroner'
  findOutNext: 'https://www.gov.uk/wills-probate-inheritance/once-the-grants-been-issued'
  whoInherits: 'https://www.gov.uk/inherits-someone-dies-without-will'
  ifYoureAnExecutor: 'https://www.gov.uk/wills-probate-inheritance/if-youre-an-executor'
  renunciationForm: 'https://www.gov.uk/government/publications/form-pa15-apply-for-renunciation-will'
  assessingMentalCapacity: 'https://www.gov.uk/make-decisions-for-someone/assessing-mental-capacity'
  myAbilityLink: 'https://mcmw.abilitynet.org.uk/'
  equalityAdvisorLink: 'https://www.equalityadvisoryservice.com/'
  wcag21Link: 'https://www.w3.org/TR/WCAG21/'
  ihtChecker: 'https://www.gov.uk/valuing-estate-of-someone-who-died/estimate-estate-value'
  ihtThreshold: 'https://www.gov.uk/inheritance-tax'
  ihtTransferOfThreshold: 'https://www.gov.uk/guidance/inheritance-tax-transfer-of-threshold'
  ihtNoInheritanceTax: 'https://www.gov.uk/valuing-estate-of-someone-who-died/check-type-of-estate'
  ihtGifts: 'https://www.gov.uk/inheritance-tax/gifts'
  spouseGivingUpAdminRightsPA16Link: 'https://www.gov.uk/government/publications/form-pa16-give-up-probate-administrator-rights'
utils:
  api:
    retries: 10
    retryDelay: 1000
payment:
  serviceId: 'PROBATE'
  siteId: 'P223'
  version: '1'
  currency: 'GBP'
noHeaderLinksPages: ['/time-out', '/sign-out', '/co-applicant-start-page', '/co-applicant-declaration', '/co-applicant-agree-page', '/co-applicant-disagree-page', '/co-applicant-all-agreed-page', '/pin-resend', '/pin-sent', '/sign-in']
alwaysWhitelistedPages: ['/time-out', '/sign-out', '/contact-us', '/accessibility-statement', '/terms-conditions', '/privacy-policy', '/cookies', '/health', '/stop-page', '/error', '/avaya-webchat']
whitelistedPagesAfterSubmission: ['/documents', '/thank-you', '/check-answers-pdf', '/declaration-pdf']
whitelistedPagesAfterPayment: ['/payment-status', '/documents', '/thank-you', '/check-answers-pdf', '/declaration-pdf']
whitelistedPagesAfterDeclaration: ['/task-list', '/executors-invites-sent', '/copies-uk', '/assets-overseas', '/copies-overseas', '/copies-summary', '/payment-breakdown', '/payment-status', '/documents', '/thank-you', '/check-answers-pdf', '/declaration-pdf', '/equality-and-diversity']
blacklistedPagesBeforeDeclaration: ['/executors-invites-sent', '/copies-uk', '/assets-overseas', '/copies-overseas', '/copies-summary', '/payment-breakdown', '/payment-status', '/documents', '/thank-you', '/check-answers-pdf', '/declaration-pdf']
probateScreenersDeathCertificateInEnglish:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionYes'
  domicile: 'optionYes'
  completed: 'optionYes'
  left: 'optionYes'
  original: 'optionYes'
  executor: 'optionYes'
  mentalCapacity: 'optionYes'
probateScreenersDeathCertificateNotInEnglish:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionNo'
  deathCertificateTranslation: 'optionYes'
  domicile: 'optionYes'
  completed: 'optionYes'
  left: 'optionYes'
  original: 'optionYes'
  executor: 'optionYes'
  mentalCapacity: 'optionYes'
probateScreenersDeathCertificateInEnglishExceptedEstates:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionYes'
  domicile: 'optionYes'
  eeDeceasedDod: 'optionYes'
  eeEstateValued: 'optionYes'
  left: 'optionYes'
  original: 'optionYes'
  executor: 'optionYes'
  mentalCapacity: 'optionYes'
probateScreenersDeathCertificateNotInEnglishExceptedEstates:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionNo'
  deathCertificateTranslation: 'optionYes'
  domicile: 'optionYes'
  eeDeceasedDod: 'optionYes'
  eeEstateValued: 'optionYes'
  left: 'optionYes'
  original: 'optionYes'
  executor: 'optionYes'
  mentalCapacity: 'optionYes'
probateScreenersDeathCertificateInEnglishDodBeforeThresholdExceptedEstates:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionYes'
  domicile: 'optionYes'
  eeDeceasedDod: 'optionNo'
  completed: 'optionYes'
  left: 'optionYes'
  original: 'optionYes'
  executor: 'optionYes'
  mentalCapacity: 'optionYes'
probateScreenersDeathCertificateNotInEnglishDodBeforeThresholdExceptedEstates:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionNo'
  deathCertificateTranslation: 'optionYes'
  domicile: 'optionYes'
  eeDeceasedDod: 'optionNo'
  completed: 'optionYes'
  left: 'optionYes'
  original: 'optionYes'
  executor: 'optionYes'
  mentalCapacity: 'optionYes'
intestacyScreenersDeathCertificateInEnglish:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionYes'
  domicile: 'optionYes'
  completed: 'optionYes'
  left: 'optionNo'
  diedAfter: 'optionYes'
  related: 'optionYes'
  otherApplicants: 'optionNo'
intestacyScreenersDeathCertificateNotInEnglish:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionNo'
  deathCertificateTranslation: 'optionYes'
  domicile: 'optionYes'
  completed: 'optionYes'
  left: 'optionNo'
  diedAfter: 'optionYes'
  related: 'optionYes'
  otherApplicants: 'optionNo'
intestacyScreenersDeathCertificateInEnglishExceptedEstates:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionYes'
  domicile: 'optionYes'
  eeDeceasedDod: 'optionYes'
  eeEstateValued: 'optionYes'
  left: 'optionNo'
  diedAfter: 'optionYes'
  related: 'optionYes'
  otherApplicants: 'optionNo'
intestacyScreenersDeathCertificateNotInEnglishExceptedEstates:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionNo'
  deathCertificateTranslation: 'optionYes'
  domicile: 'optionYes'
  eeDeceasedDod: 'optionYes'
  eeEstateValued: 'optionYes'
  left: 'optionNo'
  diedAfter: 'optionYes'
  related: 'optionYes'
  otherApplicants: 'optionNo'
intestacyScreenersDeathCertificateInEnglishDodBeforeThresholdExceptedEstates:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionYes'
  domicile: 'optionYes'
  eeDeceasedDod: 'optionNo'
  completed: 'optionYes'
  left: 'optionNo'
  diedAfter: 'optionYes'
  related: 'optionYes'
  otherApplicants: 'optionNo'
intestacyScreenersDeathCertificateNotInEnglishDodBeforeThresholdExceptedEstates:
  deathCertificate: 'optionYes'
  deathCertificateInEnglish: 'optionNo'
  deathCertificateTranslation: 'optionYes'
  domicile: 'optionYes'
  eeDeceasedDod: 'optionNo'
  completed: 'optionYes'
  left: 'optionNo'
  diedAfter: 'optionYes'
  related: 'optionYes'
  otherApplicants: 'optionNo'
hardStopParams:
  gop: []
  intestacy: []
nonIdamPages: ['health/*', 'stop-page/*', 'error', 'sign-in', 'pin-resend', 'pin-sent', 'co-applicant-*', 'pin', 'inviteIdList', 'start-eligibility', 'death-certificate', 'death-certificate-english', 'death-certificate-translation', 'deceased-domicile', 'iht-completed', 'will-left', 'will-original', 'applicant-executor', 'mental-capacity', 'died-after-october-2014', 'related-to-deceased', 'other-applicants', 'start-apply', 'contact-us', 'accessibility-statement', 'terms-conditions', 'privacy-policy', 'cookies', 'avaya-webchat', 'ee-deceased-dod', 'ee-estate-valued']
noCcdCaseIdPages: ['health/*', 'stop-page/*', 'error', 'sign-in', 'pin-resend', 'pin-sent', 'co-applicant-*', 'pin', 'inviteIdList', 'start-eligibility', 'death-certificate','death-certificate-english', 'death-certificate-translation', 'deceased-domicile', 'iht-completed', 'will-left', 'will-original', 'applicant-executor', 'mental-capacity', 'died-after-october-2014', 'related-to-deceased', 'other-applicants', 'start-apply', 'contact-us', 'accessibility-statement', 'terms-conditions', 'privacy-policy', 'cookies', 'dashboard', 'sign-out', 'time-out', 'avaya-webchat', 'ee-deceased-dod', 'ee-estate-valued']
endpoints:
  health: '/health'
  info: '/info'
appInsights:
  instrumentationKey:
documentUpload:
  validMimeTypes: ['image/jpeg', 'image/bmp', 'image/tiff', 'image/png', 'application/pdf']
  maxFiles: 10
  maxSizeBytes: 10485760 # 10 MB
  maxSizeBytesTest: 10240 # 10 KB
  paths:
    upload: '/documents/upload'
    remove: '/documents/delete'
  error:
    invalidFileType: 'Error: invalid file type'
    maxSize: 'Error: invalid file size'
    maxFiles: 'Error: too many files'
    nothingUploaded: 'Error: no files passed'
    uploadFailed: 'Error: upload failed'
    uploadTimeout: 'Error: upload timed out'
  timeoutMs: 300000
pdf:
  template:
    checkAnswers: 'checkAnswersSummary'
    declaration: 'legalDeclaration'
    coverSheet: 'bulkScanCoversheet'
  path: '/documents/generate'
  timeoutMs: 30000
assetsValueThreshold: [
  {
    minDate: '2014-10-01',
    maxDate: '2020-02-05',
    value: 250000
  },
  {
    minDate: '2020-02-06',
    value: 270000
  }
]
exceptedEstateDateOfDeath: '2022-01-01'
estateQualifyingValueRange:
  min: 325000
  max: 650000
gopOnlyPages: [
  '/deceased-name',
  '/deceased-dob',
  '/deceased-dod',
  '/will-codicils',
  '/codicils-number',
  '/deceased-married',
  '/applicant-name-as-on-will',
  '/applicant-alias',
  '/applicant-alias-reason',
  '/executors-additional-invite',
  '/executors-additional-invite-sent',
  '/executor-address',
  '/executor-address/*',
  '/executors-alias',
  '/executors-all-alive',
  '/other-executors-applying',
  '/executors-change-made',
  '/executor-contact-details',
  '/executor-contact-details/*',
  '/executor-current-name',
  '/executor-current-name/*',
  '/executor-current-name-reason',
  '/executor-current-name-reason/*',
  '/executors-dealing-with-estate',
  '/executors-invite',
  '/executors-invites-sent',
  '/executors-names',
  '/executor-notified',
  '/executor-notified/*',
  '/executors-number',
  '/executors-other-names',
  '/executor-roles',
  '/executor-roles/*',
  '/executors-update-invite',
  '/executors-update-invite-sent',
  '/executor-when-died',
  '/executor-when-died/*',
  '/executors-who-died'
]
intestacyOnlyPages: [
  '/deceased-details',
  '/assets-outside-england-wales',
  '/value-assets-outside-england-wales',
  '/deceased-marital-status',
  '/deceased-divorce-or-separation-place',
  '/relationship-to-deceased',
  '/adoption-place',
  '/spouse-not-applying-reason',
  '/any-children',
  '/any-other-children',
  '/all-children-over-18',
  '/any-deceased-children',
  '/any-grandchildren-under-18'
]
eventDescriptionPrefix: 'Page completed: '
